export { default as Header } from "./Header";
export { default as PageLayout } from "./PageLayout";
export { default as Board } from "./Board";
export { default as Post } from "./Post";
export { default as Comment } from "./Comment";
export { default as CommentInput } from "./CommentInput";
export { default as ReplyInput } from "./ReplyInput";
export { default as ProfileImage } from "./ProfileImage";
export { default as Quit } from "./Quit";
